### ISSUE TITLE
bug copying coordinates was not translated, and the name of the world is also copied to the clipboard

### ISSUE THREAD

**Issue by Disguys** [TheOneAndOnlyDanSan/DeathLocation#6]
Thanks for update, the color of the message can be changed.
But for some reason, the message about copying coordinates was not translated, and the name of the world is also copied to the clipboard.
![image](https://user-images.githubusercontent.com/60795989/183052517-2f2f3072-6a12-4cb8-bc0d-1c2bee7c2441.png)

**Comment by TheOneAndOnlyDanSan** [comment]
i'll add an option to toggle the dimension and i'll fix the bug

**Comment by Disguys** [comment]
Thanks❤️

**Comment by Disguys** [comment]
When you release a new version, please make another backport on 1.18.2
