### ISSUE TITLE
Backport on 1.18.2

### ISSUE THREAD

**Issue by Disguys** [TheOneAndOnlyDanSan/DeathLocation#7]
@TheOneAndOnlyDanSan Everything works good, please do a backport on 1.18.2

**Comment by Disguys** [comment]
I would also recommend that you upload the mods to Modrinth so that you can also gain an audience for your mods there.
https://modrinth.com/mods

**Comment by TheOneAndOnlyDanSan** [comment]
i'll make a 1.18 version and try to upload the mod on modrinth soon
